# coding: utf-8

"""
    letsrolld API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_directors_get(self) -> None:
        """Test case for directors_get

        Get Directors  # noqa: E501
        """
        pass

    def test_directors_id_get(self) -> None:
        """Test case for directors_id_get

        Get Director  # noqa: E501
        """
        pass

    def test_films_get(self) -> None:
        """Test case for films_get

        Get Films  # noqa: E501
        """
        pass

    def test_films_id_get(self) -> None:
        """Test case for films_id_get

        Get Film  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
