# coding: utf-8

"""
    letsrolld API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.director import Director  # noqa: E501

class TestDirector(unittest.TestCase):
    """Director unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Director:
        """Test Director
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Director`
        """
        model = Director()  # noqa: E501
        if include_optional:
            return Director(
                id = 56,
                name = '',
                lb_url = '',
                films = [
                    openapi_client.models.director_films_inner.Director_films_inner(
                        id = 56, 
                        title = '', 
                        description = '', 
                        year = 56, 
                        rating = '', 
                        runtime = 56, 
                        lb_url = '', 
                        jw_url = '', 
                        genres = [
                            ''
                            ], 
                        countries = [
                            ''
                            ], 
                        offers = [
                            ''
                            ], 
                        directors = [
                            56
                            ], )
                    ]
            )
        else:
            return Director(
                name = '',
        )
        """

    def testDirector(self):
        """Test Director"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
