# coding: utf-8

"""
    letsrolld API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from openapi_client.models.director_films_inner import DirectorFilmsInner

class Director(BaseModel):
    """
    Director
    """
    id: Optional[StrictInt] = None
    name: StrictStr = Field(...)
    lb_url: Optional[StrictStr] = None
    films: Optional[conlist(DirectorFilmsInner)] = None
    __properties = ["id", "name", "lb_url", "films"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Director:
        """Create an instance of Director from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in films (list)
        _items = []
        if self.films:
            for _item in self.films:
                if _item:
                    _items.append(_item.to_dict())
            _dict['films'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Director:
        """Create an instance of Director from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Director.parse_obj(obj)

        _obj = Director.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "lb_url": obj.get("lb_url"),
            "films": [DirectorFilmsInner.from_dict(_item) for _item in obj.get("films")] if obj.get("films") is not None else None
        })
        return _obj


